// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5D_bkhdbmeOCDO3gqZ-vrNhMsMr4dfQA',
    appId: '1:77655973402:web:411fcefe541a126dd97ba3',
    messagingSenderId: '77655973402',
    projectId: 'chat-app-1dc59',
    authDomain: 'chat-app-1dc59.firebaseapp.com',
    storageBucket: 'chat-app-1dc59.appspot.com',
    measurementId: 'G-99P4MTPW1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUZOSLy4GhFhN2yXtnqznsJPRS9TdXgU',
    appId: '1:77655973402:android:78fdd5ebb79fbf65d97ba3',
    messagingSenderId: '77655973402',
    projectId: 'chat-app-1dc59',
    storageBucket: 'chat-app-1dc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWNwGLqHK5WVtQpLXPaQNj-SwCQWufJw8',
    appId: '1:77655973402:ios:92ac873458a0c4bcd97ba3',
    messagingSenderId: '77655973402',
    projectId: 'chat-app-1dc59',
    storageBucket: 'chat-app-1dc59.appspot.com',
    iosClientId: '77655973402-7vgd99pc9reqe09q53stdihp5n27h8ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWNwGLqHK5WVtQpLXPaQNj-SwCQWufJw8',
    appId: '1:77655973402:ios:4a12813b83679795d97ba3',
    messagingSenderId: '77655973402',
    projectId: 'chat-app-1dc59',
    storageBucket: 'chat-app-1dc59.appspot.com',
    iosClientId: '77655973402-dmpuebm0ul9gim01j5qecpa2rel43730.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingapp.RunnerTests',
  );
}
